done some adjustment to improve the button atom
m3ntorship/pickify-frontend pull request #179
Opened 2021-06-10 00:53 UTC by ahmedelsayad11

-modified the name structure
- added the (...props) to allow usability of the component

2021-06-10 05:36 UTC, Nilegfx requested changes
can you please elaborate on the motive behind this PR?
this change enables any props to be passed to the Button component which is kind of anti-pattern. why would you do so and not being more specific about the reusable props you pass?

2021-06-10 12:14 UTC, ahmedelsayad11 commented
we faced some problem when trying to use this atom later, some button in the design does not match the atom (button) in Figma, 
[like the button of the post creation in the mobile view, it does have different padding than all other button and the cancel button too, have a different background and text color  so on ]
so I had to make it more flexible so we can reuse it again, besides the style we face another problem with the type of the button
it was made to be [type='button '] but happened to use it as a [type='submit'] and when I tried to make it accept a prop as the value for the [type], husky gave me an error, that I should write a static type for the button, so the way to make it work as we want to make whoever is gonna use it have the ability to overwrite the type of the button.
- to sum up these changes' purpose is to make the button more reusable.

2021-06-10 12:42 UTC, Nilegfx commented
@elhaw please check this PR when you have some time.

2021-06-10 20:37 UTC, elhaw requested changes
- The naming conventions for this component `ButtonArrowDown` misleading. It indicates to be a button but it is an image

2021-06-10 20:37 UTC, elhaw commented on modules/shared/components/atoms/Button/Button.tsx
> +  ...props
we need to remove the `...props` and the prop that we need.

2021-06-10 20:37 UTC, elhaw commented on modules/shared/components/atoms/Button/types/IButton.d.ts
> -    children?: string;
we need to add the type of the new prop.

2021-06-11 13:46 UTC, elhaw requested changes

2021-06-11 13:46 UTC, elhaw commented on modules/shared/components/atoms/Button/Button.tsx
> +          <ArowDown />
I know it was my suggestion 😂😂 to name it `<ArrowDown />` but the more explicit the better. 
`<ArrowDownIcon />` is better. or you can suggest a better one.

2021-06-11 13:46 UTC, elhaw commented on modules/shared/components/atoms/Button/types/EButton.ts
>    TEXT = 'text',
to follow the same naming conventions we need to name it `quaternary `

2021-06-11 13:46 UTC, elhaw commented on modules/shared/components/atoms/Button/types/IButton.d.ts
> +    buttonType: 'button' | 'reset' | 'submit' | undefined;
we can omit the `undefined` type value

2021-06-12 19:49 UTC, elhaw requested changes
I found this erorr in storybook 

> (51:10) /Users/abdulrahman/mystories/pickify-frontend/modules/shared/components/atoms/Button/Button.module.css The `px-xll` class does not exist, but `px-xl` does. If you're sure that `px-xll` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  49 | /* the only of it is kind  -the responsive cancel button-  */
  50 | .btn-normal.btn-quaternary {
> 51 |   @apply px-xll py-1.5;
     |          ^
  52 | }
  53 |

2021-06-12 20:26 UTC, elhaw approved these changes
LGTM

2021-06-12 20:31 UTC, elhaw approved these changes
@Nilegfx  
your  comment on this PR is  : 

> this change enables any props to be passed to the Button component which is a kind of anti-pattern. why would you do so and not being more specific about the reusable props you pass?

- we added the Required prop  `ButtonType : 'submit' | 'reset' | 'button' ` 
I will merge the PR  as you may be busy checking the changes mentioned a bove

2021-06-12 20:32 UTC, merged

2021-06-12 20:32 UTC, elhaw commented
@Nilegfx  
your  comment on this PR is  : 

> this change enables any props to be passed to the Button component which is a kind of anti-pattern. why would you do so and not being more specific about the reusable props you pass?

- we added the Required prop  `ButtonType : 'submit' | 'reset' | 'button' ` 
I will merge the PR  as you may be busy checking the changes mentioned above
if you found any issue regarding it, please comment and we will consider it.