Delete post
m3ntorship/pickify-frontend pull request #244
Opened 2021-06-28 17:39 UTC by atwfk

#242 
- created **DropDown** component with its types, storybook and tests
- created `deletePostHandler` function to delete one post from db and updated posts state
- added `getPostOptions` to handler what options will be passed to the **DropDown** comp based on the user is logged In or not
- added types and tests adjustments to the post view components based on the these updates

2021-06-29 16:12 UTC, omarawad0 requested changes
Please consider these required changes:
- the dropDown menu should be closed when the user clicks on either of :
   -  the menu options.
   - anything on the screen other than the menu options.

2021-06-29 16:12 UTC, omarawad0 commented on modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
> +  const onOptionClickHandler = (id: string): void => {
rename this as well please, **onMenuOptionClickHandler**

2021-06-29 16:12 UTC, omarawad0 commented on modules/shared/components/molecules/PostViewHeader/PostViewHeader.tsx
> +const getPostOptions = (
please change the name to **getPostMenuOptions** or a more specific descriptive name.

2021-07-05 17:43 UTC, ahmedkhitaby approved these changes
LGTM

2021-07-05 17:45 UTC, omarawad0 approved these changes

2021-07-05 17:45 UTC, merged