improve the feedback feature
m3ntorship/pickify-frontend pull request #435
Opened 2021-08-17 14:43 UTC by ahmedelsayad11

1- added the box layout to the feedback 
2- added the needed tests to the component

2021-08-17 19:06 UTC, omarawad0 requested changes

2021-08-17 19:06 UTC, omarawad0 commented on modules/shared/components/organisms/Feedback/Feedback.module.css
> -  @apply flex flex-col justify-center items-center h-15xl w-20xl;
It seems like you removed "h-15xl w-20xl" by mistake. please add them

2021-08-18 14:21 UTC, atwfk approved these changes
LGTM

2021-08-18 16:36 UTC, omarawad0 approved these changes

2021-08-18 16:36 UTC, merged