Readme Update
m3ntorship/pickify-frontend pull request #63
Opened 2021-05-10 19:07 UTC by Safei-Ashraf

Updated readme file to be more descriptive on how to use the project structure and submit issues.

2021-05-12 15:50 UTC, elhaw approved these changes
LGTM

2021-05-16 14:17 UTC, AhmedAdel999 requested changes
It doesn't render correctly as the `<` needs to be escaped.

2021-05-16 14:17 UTC, AhmedAdel999 commented on README.md
>  ### The difference between the pages/ and modules/<module-name>/pages/ folders
```suggestion
### The difference between the pages/ and modules/\<module-name>/pages/ folders
```

2021-05-16 15:20 UTC, Ali-Khamis requested changes
change all Pickly to Pickify

2021-05-20 12:31 UTC, Ali-Khamis approved these changes
LGTM

2021-05-20 15:07 UTC, merged