Text input component
m3ntorship/pickify-frontend pull request #71
Opened 2021-05-11 19:59 UTC by ahmedkhitaby

what we have done for now :
component's main code, styles, story, and types.
For the testing part, we hope to get some help with this issue because it was blocking us #56.
we tried our best to solve SVGs problems but we failed, we even tried to transform all the SVGs into ReactComponent but it was not a really good practice because it wasn't either readable or usable

2021-05-16 16:20 UTC, AhmedAdel999 requested changes

2021-05-16 16:20 UTC, AhmedAdel999 commented on modules/shared/components/TextInputs/TextInput.tsx
> +              className="bg-transparent focus:outline-none"
Remove the classNames and add them using the css module file.

2021-05-16 16:20 UTC, AhmedAdel999 commented on modules/shared/components/TextInputs/types/ITextInputs.d.ts
> +    label: string;
Label should be optional.

2021-05-16 16:45 UTC, atwfk commented
added the needed adjustments

2021-05-16 16:47 UTC, Ali-Khamis commented
i have some notices :

1. when the input is disabled the icon still shown and not even blured ( the clear icon function even when the input disabled ) and the border color keeps it's color ![Screenshot from 2021-05-16 18-30-52](https://user-images.githubusercontent.com/68826445/118405139-8fce7300-b676-11eb-8802-afe41795a7f5.png) 
2. the space doesn't match the design ![Screenshot from 2021-05-16 18-34-13](https://user-images.githubusercontent.com/68826445/118405184-d9b75900-b676-11eb-8bca-813796ccfb42.png)
3. when writing the text doesn't stop before the icon but it goes under it
![Screenshot from 2021-05-16 18-41-16](https://user-images.githubusercontent.com/68826445/118405210-00758f80-b677-11eb-9605-f2abb90caddd.png)

2021-05-16 20:35 UTC, ahmedkhitaby commented
@Ali-Khamis the required changes have been updated

2021-05-16 21:29 UTC, Ali-Khamis commented on modules/shared/components/atoms/TextInputs/TextInput.tsx
> +      {label !== undefined && (
this condition doesn't work like it should 
if there is no label giving it stills have a label element rendered
![Screenshot from 2021-05-16 23-28-13](https://user-images.githubusercontent.com/68826445/118413224-74775e00-b69e-11eb-8b1a-f135c202e5d7.png)

2021-05-16 21:34 UTC, Ali-Khamis commented
on right icon when disabled the  arrow down color doesn't match the design 
![Screenshot from 2021-05-16 23-32-41](https://user-images.githubusercontent.com/68826445/118413355-33337e00-b69f-11eb-839b-ee71806ab871.png)

2021-05-16 21:40 UTC, Ali-Khamis commented
1-on left icon when disabled and hovered the icon color changes
![Screenshot from 2021-05-16 23-36-05](https://user-images.githubusercontent.com/68826445/118413513-fb790600-b69f-11eb-9c77-7301843e2f3b.png)

2-consider adding ``cursor-not-allowed`` when the input is disabled

2021-05-17 16:15 UTC, Ali-Khamis commented
LGTM

2021-05-17 16:41 UTC, AhmedAdel999 commented
LGTM

2021-05-17 16:41 UTC, AhmedAdel999 approved these changes

2021-05-17 17:20 UTC, merged